version: '3.8'

services:
  api:
    build:
      context: api
    depends_on:
      - redis
      - dynamodb
      - postgres
    links:
      - redis
      - dynamodb
      - postgres
    env_file:
      - .env    
    volumes:
      - ./api/src:/app/src
    ports:
      - 3000:3000
  scraper:    
    image: scraper
    env_file:
      - .env
  redis:
    image: redis
  dynamodb:
    image: amazon/dynamodb-local
    volumes:
      - dynamodb-home:/var/lib/docker/dynamo/home
      - dynamodb-data:/var/lib/docker/dynamo/data
    ports:
      - 7999:7999
    entrypoint: ["java", "-Djava.library.path=./DynamoDBLocal_lib", "-jar", "DynamoDBLocal.jar", "-sharedDb", "-port", "7999"] 
  postgres:
    image: postgres:12.5-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lazyshoebotdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  dynamodb-home:
  dynamodb-data:
  postgres-data:
