version: '3.4'

services:
  nginx:
    image: 487233414922.dkr.ecr.eu-central-1.amazonaws.com/lsb-nginx:latest
    depends_on:
      - api
      - frontend
      - app-frontend
      - monitor
      - monitor-frontend
    links:
      - api
      - frontend
      - app-frontend
      - monitor
      - monitor-frontend
    ports:
      - 80:80
      - 443:443
      - 6969:6969
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  api:
    image: 487233414922.dkr.ecr.eu-central-1.amazonaws.com/lsb-api:latest
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./data/api/logs:/home/node/app/logs
    env_file: 
      - .env
  frontend:
    image: 487233414922.dkr.ecr.eu-central-1.amazonaws.com/lsb-frontend:latest
    depends_on:
      - api
    links:
      - api
  app-frontend:
    image: 487233414922.dkr.ecr.eu-central-1.amazonaws.com/lsb-app-frontend:latest
    depends_on:
      - api
    links:
      - api
  monitor:
    image: 487233414922.dkr.ecr.eu-central-1.amazonaws.com/lsb-monitor:latest
    depends_on:
      - redis
      - db
    links:
      - redis
      - db
    volumes:
      - ./data/monitor/logs:/home/node/app/logs
    env_file: 
      - .env
  monitor-frontend:
    image: 487233414922.dkr.ecr.eu-central-1.amazonaws.com/lsb-monitor-frontend:latest
    depends_on:
      - monitor
    links:
      - monitor
  db:
    image: mongo
    volumes:
      - dbVolume:/data/db
    ports:
      - 27017:27017
    env_file: 
      - .env
  redis:
    image: redis
    volumes:
      - redisVolume:/data
    ports:
      - 6379:6379

volumes:
  dbVolume:
  redisVolume: