version: '3.4'

services:
  # reverse-proxy:
  #   image: nginx:1.19.5
  #   depends_on:
  #     - api
  #     - frontend
  #   links:
  #     - api
  #     - frontend
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./nginx.dev.conf:/etc/nginx/nginx.conf
  # api:
  #   image: lsb-api
  #   depends_on:
  #     - db
  #   links:
  #     - db
  #   volumes:
  #     - ./api/src:/usr/src/app/src
  #   env_file: 
  #     - .env
  # frontend:
  #  image: lsb-frontend
  #  volumes:
  #    - ./frontend/src:/app/src
  monitor:
    image: lsb-monitor
    depends_on:
      - redis
      - db
    links:
      - redis
      - db
    volumes:
      - ./services/monitor/src:/usr/src/app/src
    env_file: 
      - .env
  db:
    image: mongo
    volumes:
      - mongoVolume:/data/db
    ports:
      - 27017:27017
    env_file: 
      - .env
  redis:
    image: redis
    volumes:
      - redisVolume:/data
    ports:
      - 6379:6379
  

volumes:
  mongoVolume:
  redisVolume: