version: '3.7'

services:
  nginx:
    image: 487233414922.dkr.ecr.eu-central-1.amazonaws.com/lsb-nginx:latest
    networks:
      - lsbNetwork
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
  api:
    image: 487233414922.dkr.ecr.eu-central-1.amazonaws.com/lsb-api:latest
    networks:
      - lsbNetwork
    env_file:
      - .env
    logging:
      driver: awslogs
      options:
        awslogs-group: api-logs
        awslogs-region: eu-central-1
        awslogs-stream: api1
  scraper:
    image: 487233414922.dkr.ecr.eu-central-1.amazonaws.com/lsb-scraper:latest
    networks:
      - lsbNetwork
    env_file:
      - .env
  redis:
    image: redis:6.2.1
    networks:
      - lsbNetwork
    volumes:
      - redisVolume:/data

volumes:
  redisVolume:
networks:
  lsbNetwork: