version: '3.4'

services:
  nginx:
    image: 487233414922.dkr.ecr.eu-central-1.amazonaws.com/lsb-nginx:latest
    depends_on:
      - api
    links:
      - api
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  api:
    image: 487233414922.dkr.ecr.eu-central-1.amazonaws.com/lsb-api:latest
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - ./data/api/logs:/home/node/app/logs
    env_file:
      - .env
  monitor:
    image: 487233414922.dkr.ecr.eu-central-1.amazonaws.com/lsb-monitor:latest
    depends_on:
      - redis
      - scraper
    links:
      - redis
      - scraper
    volumes:
      - ./data/monitor/logs:/home/node/app/logs
    env_file:
      - .env
  scraper:
    image: 487233414922.dkr.ecr.eu-central-1.amazonaws.com/lsb-scraper:latest
    ports:
      - 50069:50069
  redis:
    image: redis
    volumes:
      - redisVolume:/data
    ports:
      - 6379:6379

volumes:
  redisVolume: