version: '3.4'

services:
  nginx:
    image: 487233414922.dkr.ecr.eu-central-1.amazonaws.com/lsb-nginx:latest
    depends_on:
      - api
      - frontend
      - app-frontend
    links:
      - api
      - frontend
      - app-frontend
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  api:
    image: 487233414922.dkr.ecr.eu-central-1.amazonaws.com/lsb-api:latest
    depends_on:
      - db
    links:
      - db
    env_file: 
      - .env
    volumes:
      - ./data/api/logs:/home/node/app/logs
  frontend:
    image: 487233414922.dkr.ecr.eu-central-1.amazonaws.com/lsb-frontend:latest
    depends_on:
      - api
    links:
      - api
  app-frontend:
    image: 487233414922.dkr.ecr.eu-central-1.amazonaws.com/lsb-app-frontend:latest
    depends_on:
      - api
    links:
      - api
  # monitor:
  #   image: lsb-monitor
  #   depends_on:
  #     - redis
  #   links:
  #     - redis
  #   volumes:
  #     - ./services/monitor/src:/usr/src/app/src
  db:
    image: mongo
    volumes:
      - dbVolume:/data/db
    ports:
      - 27017:27017
    env_file: 
      - .env

volumes:
  dbVolume: